/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Category: typeof import('./src/components/mobile/wil-category-list/category.vue')['default']
    Linkage: typeof import('./src/components/mobile/wil-category-list/linkage.vue')['default']
    Normal: typeof import('./src/components/mobile/wil-list/normal.vue')['default']
    Steps: typeof import('./src/components/tv/tv-form/steps.vue')['default']
    TvForm: typeof import('./src/components/tv/tv-form/index.vue')['default']
    TvModal: typeof import('./src/components/tv/tv-modal/index.vue')['default']
    TvPage: typeof import('./src/components/tv/tv-page/index.vue')['default']
    TvScroll: typeof import('./src/components/tv/tv-scroll/index.vue')['default']
    Virtual: typeof import('./src/components/mobile/wil-list/virtual.vue')['default']
    WilBox: typeof import('./src/components/mobile/wil-box/index.vue')['default']
    WilCategoryList: typeof import('./src/components/mobile/wil-category-list/index.vue')['default']
    WilCell: typeof import('./src/components/electron/wil-cell/index.vue')['default']
    WilEmpty: typeof import('./src/components/mobile/wil-empty/index.vue')['default']
    WilForm: typeof import('./src/components/mobile/wil-form/index.vue')['default']
    WilImage: typeof import('./src/components/mobile/wil-image/index.vue')['default']
    WilList: typeof import('./src/components/mobile/wil-list/index.vue')['default']
    WilModal: typeof import('./src/components/mobile/wil-modal/index.vue')['default']
    WilNavbar: typeof import('./src/components/mobile/wil-navbar/index.vue')['default']
    WilPopover: typeof import('./src/components/electron/wil-popover/index.vue')['default']
    WilQrcode: typeof import('./src/components/mobile/wil-qrcode/index.vue')['default']
    WilSwiper: typeof import('./src/components/mobile/wil-swiper/index.vue')['default']
    WilTabs: typeof import('./src/components/mobile/wil-tabs/index.vue')['default']
    WilTitle: typeof import('./src/components/electron/wil-title/index.vue')['default']
    WilTooltip: typeof import('./src/components/electron/wil-tooltip/index.vue')['default']
    WilUpgrade: typeof import('./src/components/mobile/wil-upgrade/index.vue')['default']
    WilUploader: typeof import('./src/components/mobile/wil-uploader/index.vue')['default']
  }
}
